// Generated by CoffeeScript 1.3.3
var Color;

Color = function(fromOrR, g, b, a) {
  if (typeof g !== 'undefined') {
    return [fromOrR, g, b, typeof a === 'undefined' ? 1 : a];
  }
  if (typeof fromOrR !== 'undefined') {
    return [fromOrR[0], fromOrR[1], fromOrR[2], '3' in fromOrR ? fromOrR[3] : 1];
  }
  return [0, 0, 0, 1];
};

Color.cache = [Color(), Color(), Color(), Color()];

Color.white = Color(255, 255, 255);

Color.black = Color();

Color.set = function(result, r, g, b, a) {
  result[0] = r || 0;
  result[1] = g || 0;
  result[2] = b || 0;
  result[3] = a || 0;
  return result;
};

Color.copy = function(result, b) {
  result[0] = b[0];
  result[1] = b[1];
  result[2] = b[2];
  result[3] = b[3];
  return result;
};

Color.lerp = function(a, t, b, alpha, result) {
  result = result || a;
  result[0] = t * a[0] + (1 - t) * b[0];
  result[1] = t * a[1] + (1 - t) * b[1];
  result[2] = t * a[2] + (1 - t) * b[2];
  if (alpha > 0.05) {
    result[3] = t * a[3] + (1 - t) * b[3];
  } else {
    result[3] = a[3];
  }
  return result;
};

Color.rgba = function(a) {
  if (a[3] > 0.98) {
    return "rgb(" + (a[0] | 0) + ", " + (a[1] | 0) + ", " + (a[2] | 0) + ")";
  } else {
    return "rgba(" + (a[0] | 0) + ", " + (a[1] | 0) + ", " + (a[2] | 0) + ", " + a[3] + ")";
  }
};
