// Generated by CoffeeScript 1.3.3
var Vec2, abs, e, fn, i, pow, powIn, radCache, random, sqrt, toInOut, toOut, transition, typedArray, _i, _len, _ref;

typedArray = Float32Array;

Vec2 = function(fromOrX, y) {
  if (typeof y !== 'undefined') {
    return new typedArray([fromOrX, y]);
  } else if (typeof fromOrX !== 'undefined') {
    return new typedArray([fromOrX[0], fromOrX[1]]);
  } else {
    return new typedArray([0, 0]);
  }
};

Vec2.zero = Vec2();

Vec2.cache = [Vec2(), Vec2(), Vec2(), Vec2(), Vec2()];

radCache = [Vec2(), Vec2()];

e = 0.0001;

sqrt = Math.sqrt;

pow = Math.pow;

abs = Math.abs;

random = Math.random;

Vec2.set = function(result, x, y) {
  result[0] = x || 0;
  result[1] = y || 0;
  return result;
};

Vec2.copy = function(result, b) {
  result[0] = b[0];
  result[1] = b[1];
  return result;
};

Vec2.eq = function(a, b) {
  var d1, d2;
  d1 = abs(a[0] - b[0]);
  d2 = abs(a[1] - b[1]);
  return d1 < e && d2 < e;
};

Vec2.add = function(a, b, result) {
  result = result || a;
  result[0] = a[0] + b[0];
  result[1] = a[1] + b[1];
  return result;
};

Vec2.sub = function(a, b, result) {
  result = result || a;
  result[0] = a[0] - b[0];
  result[1] = a[1] - b[1];
  return result;
};

Vec2.mul = function(a, b, result) {
  result = result || a;
  result[0] = a[0] * b[0];
  result[1] = a[1] * b[1];
  return result;
};

Vec2.scal = function(a, scalar, result) {
  result = result || a;
  result[0] = a[0] * scalar;
  result[1] = a[1] * scalar;
  return result;
};

Vec2.norm = function(a, result, scalar) {
  var len, x, y;
  if (scalar == null) {
    scalar = 1;
  }
  result = result || a;
  x = a[0];
  y = a[1];
  len = scalar / (sqrt(x * x + y * y) || 1);
  result[0] = x * len;
  result[1] = y * len;
  return result;
};

Vec2.lenSq = function(a) {
  return a[0] * a[0] + a[1] * a[1];
};

Vec2.len = function(a) {
  return sqrt(a[0] * a[0] + a[1] * a[1]);
};

Vec2.dot = function(a, b) {
  return a[0] * b[0] + a[1] * b[1];
};

Vec2.cross = function(a, b) {
  return a[0] * b[1] - a[1] * b[0];
};

Vec2.lerp = function(a, b, scalar, result) {
  result = result || a;
  result[0] = a[0] + scalar * (b[0] - a[0]);
  result[1] = a[1] + scalar * (b[1] - a[1]);
  return result;
};

Vec2.dist = function(a, b) {
  var x, y;
  x = b[0] - a[0];
  y = b[1] - a[1];
  return sqrt(x * x + y * y);
};

Vec2.distSq = function(a, b) {
  var x, y;
  x = b[0] - a[0];
  y = b[1] - a[1];
  return x * x + y * y;
};

Vec2.limit = function(a, max, result) {
  var ratio, x, y;
  result = result || a;
  x = a[0];
  y = a[1];
  if ((ratio = max / sqrt(x * x + y * y)) < 1) {
    result[0] = x * ratio;
    result[1] = y * ratio;
  } else if (result !== a) {
    result[0] = x;
    result[1] = y;
  }
  return result;
};

Vec2.rad = function(a, b) {
  if (!b) {
    return Math.atan2(a[1], a[0]);
  }
  return Math.acos(Vec2.dot(Vec2.norm(a, radCache[0]), Vec2.norm(b, radCache[1])));
};

Vec2.rot = function(a, rad, result) {
  var cosA, sinA, x, y;
  result = result || a;
  sinA = Math.sin(rad);
  cosA = Math.cos(rad);
  x = a[0];
  y = a[1];
  result[0] = x * cosA - y * sinA;
  result[1] = x * sinA + y * cosA;
  return result;
};

Vec2.lookAt = function(a, b, result) {
  var len;
  result = result || a;
  len = Vec2.len(a);
  return Vec2.norm(Vec2.rot(a, Math.atan2(b[0] - a[0], b[1] - a[1]) - Math.atan2(a[1], a[0]), result), null, len);
};

Math.TAU = Math.PI * 2;

Math.UID = 1;

Math.uid = function() {
  return Math.UID++;
};

Math.clamp = function(a, low, high) {
  if (a < low) {
    return low;
  }
  if (a > high) {
    return high;
  } else {
    return a;
  }
};

Math.randomFloat = function(low, high, ease) {
  return low + (ease || Math.linear)(random()) * (high - low + 1);
};

Math.randomBool = function(chance) {
  return random() <= chance;
};

powIn = function(strength) {
  if (strength == null) {
    strength = 2;
  }
  return function(t) {
    return pow(t, strength);
  };
};

toOut = function(fn) {
  return function(t) {
    return 1 - fn(1 - t);
  };
};

toInOut = function(fn) {
  return function(t) {
    return (t < 0.5 ? fn(t * 2) : 2 - fn(2 * (1 - t))) / 2;
  };
};

Math.linear = function(t) {
  return t;
};

_ref = ['quad', 'cubic', 'quart', 'quint'];
for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
  transition = _ref[i];
  Math[transition + 'In'] = fn = powIn(i + 2);
  Math[transition + 'Out'] = toOut(fn);
  Math[transition + 'InOut'] = toInOut(fn);
}
