// Generated by CoffeeScript 1.3.3
var Renderer;

Renderer = (function() {

  function Renderer(id) {
    this.canvas = document.getElementById(id);
    this.context = this.canvas.getContext('2d');
    this.center = Vec2();
    this.size = Vec2(this.canvas.width, this.canvas.height);
  }

  Renderer.prototype.clear = function() {
    this.canvas.width = this.size[0];
    this.context.setTransform(1, 0, 0, 1, -this.center[0] + this.size[0] / 2, -this.center[1] + this.size[1] / 2);
    return this;
  };

  Renderer.prototype.setCenter = function(x, y) {
    this.center.set(Math.floor(x), Math.floor(y));
    return this;
  };

  return Renderer;

})();
