// Generated by CoffeeScript 1.3.3
var Spring,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Spring = (function() {

  function Spring() {
    this.center = Vec2();
  }

  Spring.prototype.alloc = function(owner, centerX, centerY) {
    owner.spring = this;
    owner.pubsub.sub(this, 'free');
    this.owner = owner;
    return Vec2.set(this.center, centerX, centerY);
  };

  Spring.prototype.free = function() {
    this.allocd = false;
    this.owner.pubsub.unsub(this);
    this.owner = this.owner.spring = null;
    return this;
  };

  return Spring;

})();

Pool.Springs = (function(_super) {

  __extends(Springs, _super);

  function Springs() {
    return Springs.__super__.constructor.apply(this, arguments);
  }

  Springs.prototype.instantiate = function() {
    return new Spring();
  };

  Springs.prototype.update = function(dt) {
    var center, spring, _i, _len, _ref, _ref1;
    _ref = this.roster;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      spring = _ref[_i];
      if (!spring.allocd) {
        continue;
      }
      center = ((_ref1 = spring.target) != null ? _ref1.pos : void 0) || spring.center;
      spring.update(dt);
    }
    return this;
  };

  return Springs;

})(Pool);

Spring.pool = new Pool.Springs(128);
