// Generated by CoffeeScript 1.3.3
var MAX_SPEED, World, current, dir, origin, pos;

MAX_SPEED = 150;

origin = Vec2();

current = Vec2();

pos = Vec2();

dir = Vec2();

World = (function() {

  function World() {
    this.updateQueue = [Collider.pool, Firework.pool, Particle.pool];
    this.drawQueue = [Particle.pool];
    this.pubsub = Pubsub.pool.acquire(this);
    this.firework = Firework.pool.acquire(this, Vec2(0, 0), Vec2(800, 450), Vec2(20, 20), Vec2(15, 35), Vec2(500, 500), 0.2);
    this.steps = 0;
    this.minStep = 10;
    this.gravity = Vec2(0, 500);
    this.friction = 20;
    this.drag = 0.9999;
  }

  World.prototype.update = function(delta) {
    var instance, min, _i, _len, _ref, _results;
    if (delta > 500) {
      delta = 100;
    }
    this.steps += delta;
    min = this.minStep;
    _results = [];
    while (this.steps > min) {
      this.steps -= min;
      _ref = this.updateQueue;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        instance = _ref[_i];
        instance.update(min, this);
      }
      _results.push(this);
    }
    return _results;
  };

  World.prototype.draw = function(context) {
    var instance, _i, _len, _ref;
    _ref = this.drawQueue;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      instance = _ref[_i];
      instance.draw(context, this);
    }
    return this;
  };

  return World;

})();
