// Generated by CoffeeScript 1.3.3
var MAX_SPEED, World;

MAX_SPEED = 120;

World = (function() {

  function World() {
    this.updateQueue = [Collider.pool, Particle.pool];
    this.drawQueue = [Particle.pool];
  }

  World.prototype.update = function(delta) {
    var instance, particle, _i, _len, _ref;
    if (Math.randomBool(0.7)) {
      particle = Particle.pool.acquire(Math.randomFloat(-300, 300), Math.randomFloat(-250, 250), Math.randomFloat(-MAX_SPEED, MAX_SPEED), Math.randomFloat(-MAX_SPEED, MAX_SPEED), Math.randomFloat(1500, 2500));
    }
    _ref = this.updateQueue;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      instance = _ref[_i];
      instance.update(delta);
    }
    return this;
  };

  World.prototype.draw = function(context) {
    var instance, _i, _len, _ref;
    _ref = this.drawQueue;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      instance = _ref[_i];
      instance.draw(context);
    }
    return this;
  };

  return World;

})();
