// Generated by CoffeeScript 1.6.1
var Color, Component, Engine, Explosion, Kinetic, Particle, Pool, Vec2,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require('./component');

Pool = require('./pool');

Vec2 = require('./math').Vec2;

Color = require('./color');

Kinetic = require('./kinetic');

Particle = require('./particle');

Engine = require('./engine');

Explosion = (function(_super) {

  __extends(Explosion, _super);

  Explosion.prototype.tag = 'explosion';

  Explosion.prototype.attributes = {
    lifetime: 0.4,
    maxSize: 100,
    color: Color.white
  };

  function Explosion() {
    this.color = Color();
  }

  Explosion.prototype.instantiate = function(attributes) {
    Color.copy(this.color, attributes.color);
    this.lifetime = attributes.lifetime;
    this.maxSize = attributes.maxSize;
    this.pos = this.transform.pos;
    this.age = 0;
    this.state = 'began';
    return this;
  };

  Explosion.prototype.update = function(dt, scene) {
    var acc, age, dist, factor, i, kinetic, max, particle, radius, radiusSq, _i, _j, _len, _ref;
    if (this.state === 'began') {
      max = Kinetic.maxAcc;
      radius = this.maxSize;
      radiusSq = this.maxSize * this.maxSize;
      _ref = Kinetic.pool.register;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        kinetic = _ref[_i];
        if (!(kinetic.mass && (dist = Vec2.distSq(this.pos, kinetic.pos)) < radiusSq)) {
          continue;
        }
        factor = Math.quadOut(1 - Math.sqrt(dist) / radius);
        Vec2.add(kinetic.acc, Vec2.scal(Vec2.norm(Vec2.sub(kinetic.pos, this.pos, Vec2.cache[0])), max * factor));
      }
      acc = Vec2.cache[0];
      for (i = _j = 0; _j <= 100; i = _j += 1) {
        Vec2.norm(Vec2.set(acc, Math.rand(-1, 1), Math.rand(-1, 1)), null, Math.rand(0, max));
        particle = Particle.alloc(this.root, this.pos, acc, Math.rand(this.lifetime / 2, this.lifetime * 2), Math.rand(1, 4), 0);
      }
      this.state = 'exploding';
    }
    age = (this.age += dt);
    if (age >= this.lifetime) {
      this.entity.destroy();
    } else {
      this.factor = Math.quadOut(age / this.lifetime);
      this.size = this.factor * this.maxSize;
    }
    return this;
  };

  Explosion.prototype.render = function(ctx) {
    var circles, factor, i, pos, _i;
    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    pos = this.pos;
    circles = 10;
    for (i = _i = 1; _i <= circles; i = _i += 1) {
      factor = Math.quadOut(i / circles);
      ctx.beginPath();
      ctx.arc(pos[0] | 0, pos[1] | 0, this.size * factor | 0, 0, Math.TAU, true);
      ctx.closePath();
      this.color[3] = factor * (1 - this.factor);
      ctx.lineWidth = 10 * factor;
      ctx.strokeStyle = Color.rgba(this.color);
      ctx.stroke();
    }
    ctx.restore();
    return this;
  };

  return Explosion;

})(Component);

new Pool(Explosion);

module.exports = Explosion;
