'use strict';

module.exports = {
  Boid: require('./core/boid'),
  Border: require('./core/border'),
  Bounds: require('./core/bounds'),
  Collider: require('./core/collider'),
  Color: require('./core/color'),
  Component: require('./core/component'),
  Console: require('./core/console'),
  Engine: require('./core/engine'),
  Entity: require('./core/entity'),
  Heightmap: require('./labs/heightmap'),
  Input: require('./core/input'),
  Jitter: require('./core/jitter'),
  Kinetic: require('./core/kinetic'),
  Mat2: require('./math/mat2'),
  Mathf: require('./math/mathf'),
  Particle: require('./core/particle'),
  Perlin: require('./labs/perlin'),
  Pool: require('./core/pool'),
  Prefab: require('./core/prefab'),
  Random: require('./math/random'),
  Renderer: require('./core/renderer'),
  Shims: require('./core/shims'),
  Sprite: require('./core/sprite'),
  Transform: require('./core/transform'),
  Tweens: require('./math/tweens'),
  Vec2: require('./math/vec2'),
};
