// Generated by CoffeeScript 1.4.0
var Component, Force, Pool, Vec2,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require('./component');

Pool = require('./pool');

Vec2 = require('./math').Vec2;

Force = (function(_super) {

  __extends(Force, _super);

  Force.prototype.type = 'force';

  Force.prototype.presets = {
    force: Vec2(),
    torque: 0
  };

  function Force() {
    this.force = Vec2();
  }

  Force.prototype.reset = function(presets) {
    Vec2.copy(this.force, presets.force);
    this.torque = presets.torque;
    this.age = 0;
    return this;
  };

  Force.prototype.simulate = function(dt) {
    Vec2.add(this.kinetic.acc, this.force);
    return this;
  };

  return Force;

})(Component);

new Pool(Force);

module.exports = Force;
