// Generated by CoffeeScript 1.6.1
var Component, Force, Pool, Vec2, cache,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require('./component');

Pool = require('./pool');

Vec2 = require('./math').Vec2;

cache = Vec2();

Force = (function(_super) {

  __extends(Force, _super);

  Force.prototype.tag = 'force';

  Force.prototype.attributes = {
    acc: Vec2(),
    torque: 0
  };

  function Force() {
    this.acc = Vec2();
  }

  Force.prototype.instantiate = function(attributes) {
    Vec2.copy(this.acc, attributes.acc);
    this.torque = attributes.torque;
    this.age = 0;
    return this;
  };

  Force.prototype.add = function(acc) {
    Vec2.add(this.acc, acc);
    return this;
  };

  Force.prototype.simulate = function(dt) {
    Vec2.add(this.kinetic.acc, this.acc);
    return this;
  };

  return Force;

})(Component);

new Pool(Force);

module.exports = Force;
