// Generated by CoffeeScript 1.4.0
var Component, Engine, Input, Pool, Vec2, pool,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require('./component');

Pool = require('./pool');

Vec2 = require('./math').Vec2;

Engine = require('./engine');

Input = (function(_super) {

  __extends(Input, _super);

  Input.prototype.type = 'input';

  Input.prototype.support = {
    touch: 'ontouchstart' in window,
    orientation: 'ondeviceorientation' in window
  };

  function Input() {
    var code, key, type, _ref;
    this.queue = [];
    this.locks = {};
    this.pos = Vec2();
    this.prevPos = Vec2();
    this.touchState = null;
    this.axis = Vec2();
    this.mouseAxis = Vec2();
    this.orientation = Vec2();
    this.prevOrientation = Vec2();
    this.baseOrientation = Vec2();
    this.map = {
      32: 'space',
      192: 'debug'
    };
    this.keyNames = [];
    this.keys = {};
    _ref = this.map;
    for (code in _ref) {
      key = _ref[code];
      if (!~this.keyNames.indexOf(key)) {
        this.keyNames.push(key);
        this.keys[key] = null;
      }
    }
    this.throttled = {
      mousemove: -1,
      deviceorientation: -1
    };
    this.events = this.support.touch ? {
      touchstart: 'startTouch',
      touchmove: 'moveTouch',
      touchend: 'endTouch',
      touchcancel: 'endTouch'
    } : {
      mousedown: 'startTouch',
      mousemove: 'moveTouch',
      mouseup: 'endTouch',
      keydown: 'keyStart',
      keyup: 'keyEnd'
    };
    for (type in this.events) {
      document.addEventListener(type, this, false);
    }
  }

  Input.prototype.handleEvent = function(event) {
    var type;
    if (event.metaKey) {
      return;
    }
    type = event.type;
    this.queue.push(event);
    return this;
  };

  Input.prototype.keyStart = function(event) {
    var key;
    if ((key = this.map[event.keyCode]) && !this.keys[key]) {
      this.keys[key] = 'began';
      Engine.pub('onKeyBegan', key);
    }
    return this;
  };

  Input.prototype.keyEnd = function(event) {
    var key;
    if (key = this.map[event.keyCode]) {
      this.keys[key] = 'ended';
      Engine.pub('onKeyEnded', key);
    }
    return this;
  };

  Input.prototype.startTouch = function(event) {
    if (!this.lock('touch')) {
      return false;
    }
    this.resolve(event);
    if (!this.touchState && !event.metaKey) {
      this.touchState = 'began';
      Engine.pub('onTouchBegan');
    }
    return this;
  };

  Input.prototype.moveTouch = function(event) {
    var state;
    state = this.touchState;
    if ((state === 'began' || state === 'ended') && !this.lock('touch')) {
      return false;
    }
    this.resolve(event);
    if (state && state !== 'ended' && state !== 'moved') {
      this.touchState = 'moved';
    }
    return this;
  };

  Input.prototype.endTouch = function(event) {
    if (!this.lock('touch')) {
      return false;
    }
    this.resolve(event);
    if (this.touchState && (!this.support.touch || !event.targetTouches.length)) {
      Engine.pub('onTouchEnded');
      this.touchState = 'ended';
    }
    return this;
  };

  Input.prototype.calibrateOrientation = function() {
    this.baseOrientationTime = this.orientationTime;
    Vec2.copy(this.baseOrientation, this.orientation);
    Vec2.set(this.orientation);
    return this;
  };

  Input.prototype.deviceOrientation = function(event) {
    Vec2.copy(this.prevOrientation, this.orientation);
    Vec2.sub(Vec2.set(this.orientation, event.gamma | 0, event.beta | 0), this.baseOrientation);
    this.orientationTime = event.timeStamp / 1000;
    if (!this.baseOrientationTime) {
      this.calibrateOrientation();
    }
    return this;
  };

  Input.prototype.resolve = function(event) {
    var coords, renderer;
    coords = this.support.touch ? event.targetTouches[0] : event;
    if (coords) {
      this.prevTime = this.time;
      this.time = event.timeStamp / 1000;
      Vec2.copy(this.prevPos, this.pos);
      renderer = Engine.renderer;
      Vec2.set(this.pos, (coords.pageX - renderer.margin[0]) / renderer.scale | 0, (coords.pageY - renderer.margin[1]) / renderer.scale | 0);
    }
    return this;
  };

  Input.prototype.lock = function(key) {
    if (this.locks[key] === this.frame) {
      return false;
    }
    this.locks[key] = this.frame;
    return true;
  };

  Input.prototype.lateUpdate = function(dt, scene) {
    var event, key, keys, queue, type, _i, _len, _ref;
    switch (this.touchState) {
      case 'began':
        this.touchState = 'stationary';
        break;
      case 'ended':
        this.touchState = null;
        break;
    }
    keys = this.keys;
    _ref = this.keyNames;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      switch (keys[key]) {
        case 'began':
          keys[key] = 'pressed';
          break;
        case 'ended':
          keys[key] = null;
          break;
      }
    }
    this.frame = Engine.frame;
    queue = this.queue;
    while ((event = queue[0])) {
      type = event.type;
      if (!this[this.events[type]](event)) {
        break;
      }
      queue.shift();
    }
    return this;
  };

  return Input;

})(Component);

pool = new Pool(Input);

module.exports = Input;
