// Generated by CoffeeScript 1.5.0
var Component, Jitter, Pool, Vec2,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require('./component');

Pool = require('./pool');

Vec2 = require('./math').Vec2;

Jitter = (function(_super) {

  __extends(Jitter, _super);

  function Jitter() {
    Jitter.__super__.constructor.apply(this, arguments);
  }

  Jitter.prototype.type = 'jitter';

  Jitter.prototype.presets = {
    factor: 0.8,
    force: 1000
  };

  Jitter.prototype.reset = function(presets) {
    this.factor = presets.factor, this.force = presets.force;
    return this;
  };

  Jitter.prototype.fixedUpdate = function(dt) {
    var rand;
    if (Math.chance(this.factor)) {
      rand = Vec2.set(Vec2.cache[0], Math.rand(-this.force, this.force), Math.rand(-this.force, this.force));
      return Vec2.add(this.parent.kinetic.acc, rand);
    }
  };

  return Jitter;

})(Component);

new Pool(Jitter);

module.exports = Jitter;
