// Generated by CoffeeScript 1.6.1
var EPSILON, Mat2, Mth, Vec2, abs, fn, i, objCache, objVecCache, pow, powIn, radCache, random, sqrt, toInOut, toOut, transition, typedArray, _i, _len, _ref;

Mth = Math;

sqrt = Mth.sqrt, pow = Mth.pow, abs = Mth.abs, random = Mth.random, random = Mth.random, pow = Mth.pow;

Mth.EPSILON = EPSILON = 0.001;

Mth.TAU = Mth.PI * 2;

Mth.PIRAD = 0.0174532925;

Mth.UID = 1;

Mth.uid = function() {
  return Mth.UID++;
};

Mth.clamp = function(a, low, high) {
  if (a < low) {
    return low;
  }
  if (a > high) {
    return high;
  } else {
    return a;
  }
};

Mth.rand = function(low, high, ease) {
  return (ease || Mth.linear)(random()) * (high - low) + low;
};

Mth.randArray = function(array) {
  return array[random() * array.length | 0];
};

Mth.chance = function(chance) {
  return random() <= chance;
};

powIn = function(strength) {
  if (strength == null) {
    strength = 2;
  }
  return function(t) {
    return pow(t, strength);
  };
};

toOut = function(fn) {
  return function(t) {
    return 1 - fn(1 - t);
  };
};

toInOut = function(fn) {
  return function(t) {
    return (t < 0.5 ? fn(t * 2) : 2 - fn(2 * (1 - t))) / 2;
  };
};

Mth.linear = function(t) {
  return t;
};

_ref = ['quad', 'cubic', 'quart', 'quint'];
for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
  transition = _ref[i];
  Mth[transition + 'In'] = fn = powIn(i + 2);
  Mth[transition + 'Out'] = toOut(fn);
  Mth[transition + 'InOut'] = toInOut(fn);
}

Mth.TypedArray = typedArray = Float64Array || Float32Array || function(arr) {
  return arr;
};

Mth.Vec2 = Vec2 = function(fromOrX, y) {
  if (y != null) {
    return new typedArray([fromOrX, y]);
  }
  if (fromOrX != null) {
    return new typedArray(fromOrX);
  }
  return new typedArray(Vec2.zero);
};

Vec2.zero = Vec2.center = Vec2(0, 0);

Vec2.cache = [Vec2(), Vec2(), Vec2(), Vec2(), Vec2()];

Vec2.topLeft = Vec2(-1, -1);

Vec2.topCenter = Vec2(0, -1);

Vec2.topRight = Vec2(1, -1);

Vec2.centerLeft = Vec2(-1, 0);

Vec2.centerRight = Vec2(1, 0);

Vec2.bottomLeft = Vec2(-1, 1);

Vec2.bottomCenter = Vec2(0, 1);

Vec2.bottomRight = Vec2(1, 1);

radCache = [Vec2(), Vec2()];

objCache = {
  x: 0,
  y: 0
};

objVecCache = Vec2();

Vec2.set = function(result, x, y) {
  result[0] = x || 0;
  result[1] = y || 0;
  return result;
};

Vec2.copy = function(result, b) {
  result[0] = b[0];
  result[1] = b[1];
  return result;
};

Vec2.valid = function(a) {
  return !(isNaN(a[0]) || isNaN(a[1]));
};

Vec2.toString = function(a) {
  return "[" + a[0] + ", " + a[1] + "]";
};

Vec2.fromObj = function(obj, a) {
  a || (a = objVecCache);
  a[0] = obj.x;
  a[1] = obj.y;
  return a;
};

Vec2.toObj = function(a, obj) {
  obj || (obj = objCache);
  obj.x = a[0];
  obj.y = a[1];
  return obj;
};

Vec2.eq = function(a, b) {
  return abs(a[0] - b[0]) < EPSILON && abs(a[1] - b[1]) < EPSILON;
};

Vec2.add = function(a, b, result) {
  result || (result = a);
  result[0] = a[0] + b[0];
  result[1] = a[1] + b[1];
  return result;
};

Vec2.sub = function(a, b, result) {
  result || (result = a);
  result[0] = a[0] - b[0];
  result[1] = a[1] - b[1];
  return result;
};

Vec2.mul = function(a, b, result) {
  result || (result = a);
  result[0] = a[0] * b[0];
  result[1] = a[1] * b[1];
  return result;
};

Vec2.scal = function(a, scalar, result) {
  result || (result = a);
  result[0] = a[0] * scalar;
  result[1] = a[1] * scalar;
  return result;
};

Vec2.norm = function(a, result, scalar) {
  var len, x, y;
  result || (result = a);
  x = a[0];
  y = a[1];
  len = (scalar || 1) / (sqrt(x * x + y * y) || 1);
  result[0] = x * len;
  result[1] = y * len;
  return result;
};

Vec2.lenSq = function(a) {
  return a[0] * a[0] + a[1] * a[1];
};

Vec2.len = function(a) {
  return sqrt(a[0] * a[0] + a[1] * a[1]);
};

Vec2.dot = function(a, b) {
  return a[0] * b[0] + a[1] * b[1];
};

Vec2.cross = function(a, b) {
  return a[0] * b[1] - a[1] * b[0];
};

Vec2.lerp = function(a, b, scalar, result) {
  result || (result = a);
  result[0] = a[0] + scalar * (b[0] - a[0]);
  result[1] = a[1] + scalar * (b[1] - a[1]);
  return result;
};

Vec2.max = function(a, b, axis) {
  if (axis != null) {
    if (a[axis] > b[axis]) {
      return a;
    } else {
      return b;
    }
  }
  if (Vec2.lenSq(a) > Vec2.lenSq(b)) {
    return a;
  } else {
    return b;
  }
};

Vec2.perp = function(a, result) {
  var x;
  result || (result = a);
  x = a[0];
  result[0] = a[1];
  result[1] = -x;
  return result;
};

Vec2.dist = function(a, b) {
  var x, y;
  x = b[0] - a[0];
  y = b[1] - a[1];
  return sqrt(x * x + y * y);
};

Vec2.distSq = function(a, b) {
  var x, y;
  x = b[0] - a[0];
  y = b[1] - a[1];
  return x * x + y * y;
};

Vec2.limit = function(a, max, result) {
  var ratio, x, y;
  result || (result = a);
  x = a[0];
  y = a[1];
  if ((ratio = max / sqrt(x * x + y * y)) < 1) {
    result[0] = x * ratio;
    result[1] = y * ratio;
  } else if (result !== a) {
    result[0] = x;
    result[1] = y;
  }
  return result;
};

Vec2.rad = function(a, b) {
  if (!b) {
    return Mth.atan2(a[1], a[0]);
  }
  return Mth.acos(Vec2.dot(Vec2.norm(a, radCache[0]), Vec2.norm(b, radCache[1])));
};

Vec2.rot = function(a, theta, result) {
  var cosA, sinA, x, y;
  result || (result = a);
  sinA = Mth.sin(theta);
  cosA = Mth.cos(theta);
  x = a[0];
  y = a[1];
  result[0] = x * cosA - y * sinA;
  result[1] = x * sinA + y * cosA;
  return result;
};

Vec2.rotAxis = function(a, b, theta, result) {
  return Vec2.add(Vec2.rot(Vec2.sub(a, b, result || a), theta), b);
};

Vec2.lookAt = function(a, b, result) {
  var len;
  len = Vec2.len(a);
  return Vec2.norm(Vec2.rot(a, Mth.atan2(b[0] - a[0], b[1] - a[1]) - Mth.atan2(a[1], a[0]), result || a), null, len);
};

Vec2.variant = function(a, delta, result) {
  result || (result = a);
  result[0] = a[0] + Math.rand(-delta, delta);
  result[1] = a[1] + Math.rand(-delta, delta);
  return result;
};

module.exports.Vec2 = Vec2;

Mth.Mat2 = Mat2 = function(fromOrA, b, c, d, tx, ty) {
  if (b != null) {
    return new typedArray([fromOrA, b, c, d, tx, ty]);
  }
  if (fromOrA != null) {
    return new typedArray(fromOrA);
  }
  return new typedArray(Mat2.identity);
};

Mat2.identity = Mat2(1, 0, 0, 1, 0, 0);

Mat2.set = function(result, a, b, c, d, tx, ty) {
  result[0] = a || 0;
  result[1] = b || 0;
  result[2] = c || 0;
  result[3] = d || 0;
  result[4] = tx || 0;
  result[5] = ty || 0;
  return result;
};

Mat2.copy = function(result, b) {
  result[0] = b[0];
  result[1] = b[1];
  result[2] = b[2];
  result[3] = b[3];
  result[4] = b[4];
  result[5] = b[5];
  return result;
};

Mat2.valid = function(a) {
  return !(isNaN(a[0]) || isNaN(a[1]) || isNaN(a[2]) || isNaN(a[3]) || isNaN(a[4]) || isNaN(a[5]));
};

Mat2.toString = function(a) {
  return "[" + a[0] + ", " + a[1] + " | " + a[2] + ", " + a[3] + " | " + a[4] + ", " + a[5] + "]";
};

Mat2.mul = function(a, b, result) {
  var aa, ab, ac, ad, atx, aty, ba, bb, bc, bd, btx, bty;
  result || (result = a);
  aa = a[0];
  ab = a[1];
  ac = a[2];
  ad = a[3];
  atx = a[4];
  aty = a[5];
  ba = b[0];
  bb = b[1];
  bc = b[2];
  bd = b[3];
  btx = b[4];
  bty = b[5];
  result[0] = aa * ba + ab * bc;
  result[1] = aa * bb + ab * bd;
  result[2] = ac * ba + ad * bc;
  result[3] = ac * bb + ad * bd;
  result[4] = ba * atx + bc * aty + btx;
  result[5] = bb * atx + bd * aty + bty;
  return result;
};

Mat2.rot = function(a, rad, result) {
  var aa, ab, ac, ad, atx, aty, ct, st;
  result || (result = a);
  aa = a[0];
  ab = a[1];
  ac = a[2];
  ad = a[3];
  atx = a[4];
  aty = a[5];
  st = Mth.sin(rad);
  ct = Mth.cos(rad);
  result[0] = aa * ct + ab * st;
  result[1] = -aa * st + ab * ct;
  result[2] = ac * ct + ad * st;
  result[3] = -ac * st + ct * ad;
  result[4] = ct * atx + st * aty;
  result[5] = ct * aty - st * atx;
  return result;
};

Mat2.scal = function(a, v, result) {
  var vx, vy;
  result || (result = a);
  vx = v[0];
  vy = v[1];
  result[0] = a[0] * vx;
  result[1] = a[1] * vy;
  result[2] = a[2] * vx;
  result[3] = a[3] * vy;
  result[4] = a[4] * vx;
  result[5] = a[5] * vy;
  return result;
};

Mat2.trans = function(a, v, result) {
  result || (result = a);
  result[0] = a[0];
  result[1] = a[1];
  result[2] = a[2];
  result[3] = a[3];
  result[4] = a[4] + v[0];
  result[5] = a[5] + v[1];
  return result;
};

module.exports.Mat2 = Mat2;
