// Generated by CoffeeScript 1.6.1
var Component, Pool, Seek, Vec2,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require('./component');

Pool = require('./pool');

Vec2 = require('./math').Vec2;

Seek = (function(_super) {

  __extends(Seek, _super);

  function Seek() {
    return Seek.__super__.constructor.apply(this, arguments);
  }

  Seek.prototype.type = 'seek';

  Seek.prototype.presets = {
    targets: null
  };

  Seek.prototype.reset = function(presets) {
    this.targets = presets.targets;
    this.roster = Pool.types[this.targets];
    return this;
  };

  Seek.prototype.fixedUpdate = function(dt) {
    return this;
  };

  return Seek;

})(Component);

new Pool(Seek);

module.exports = Seek;
